[{'name': 'specific_data.data.name', 'title': 'Asset Name', 'type': 'string'},
 {'name': 'specific_data.data.hostname',
  'title': 'Host Name',
  'type': 'string'},
 {'name': 'specific_data.data.description',
  'title': 'Description',
  'type': 'string'},
 {'format': 'date-time',
  'name': 'specific_data.data.last_seen',
  'title': 'Last Seen',
  'type': 'string'},
 {'format': 'date-time',
  'name': 'specific_data.data.fetch_time',
  'title': 'Fetch Time',
  'type': 'string'},
 {'format': 'table',
  'items': [{'name': 'name', 'title': 'Iface Name', 'type': 'string'},
            {'name': 'mac', 'title': 'Mac', 'type': 'string'},
            {'name': 'manufacturer', 'title': 'Manufacturer', 'type': 'string'},
            {'format': 'ip',
             'items': {'format': 'ip', 'type': 'string'},
             'name': 'ips',
             'title': 'IPs',
             'type': 'array'},
            {'description': 'A list of subnets in ip format, that correspond '
                            'the IPs',
             'format': 'subnet',
             'items': {'format': 'subnet', 'type': 'string'},
             'name': 'subnets',
             'title': 'Subnets',
             'type': 'array'},
            {'description': 'A list of vlans in this interface',
             'items': [{'name': 'name', 'title': 'Vlan Name', 'type': 'string'},
                       {'name': 'tagid', 'title': 'Tag ID', 'type': 'integer'},
                       {'enum': ['Tagged', 'Untagged'],
                        'name': 'tagness',
                        'title': 'Vlan Tagness',
                        'type': 'string'}],
             'name': 'vlan_list',
             'title': 'Vlans',
             'type': 'array'},
            {'branched': True,
             'name': 'vlan_list.name',
             'title': 'Vlans: Vlan Name',
             'type': 'string'},
            {'branched': True,
             'name': 'vlan_list.tagid',
             'title': 'Vlans: Tag ID',
             'type': 'integer'},
            {'branched': True,
             'enum': ['Tagged', 'Untagged'],
             'name': 'vlan_list.tagness',
             'title': 'Vlans: Vlan Tagness',
             'type': 'string'},
            {'enum': ['Up',
                      'Down',
                      'Testing',
                      'Unknown',
                      'Dormant',
                      'Nonpresent',
                      'LowerLayerDown'],
             'name': 'operational_status',
             'title': 'Operational Status',
             'type': 'string'},
            {'enum': ['Up', 'Down'],
             'name': 'admin_status',
             'title': 'Admin Status',
             'type': 'string'},
            {'description': 'Interface max speed per Second',
             'name': 'speed',
             'title': 'Interface Speed',
             'type': 'string'},
            {'enum': ['Access', 'Trunk'],
             'name': 'port_type',
             'title': 'Port Type',
             'type': 'string'},
            {'description': 'Interface Maximum transmission unit',
             'name': 'mtu',
             'title': 'MTU',
             'type': 'string'}],
  'name': 'specific_data.data.network_interfaces',
  'title': 'Network Interfaces',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.network_interfaces.name',
  'title': 'Network Interfaces: Iface Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.network_interfaces.mac',
  'title': 'Network Interfaces: Mac',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.network_interfaces.manufacturer',
  'title': 'Network Interfaces: Manufacturer',
  'type': 'string'},
 {'format': 'ip',
  'items': {'format': 'ip', 'type': 'string'},
  'name': 'specific_data.data.network_interfaces.ips',
  'title': 'Network Interfaces: IPs',
  'type': 'array'},
 {'description': 'A list of subnets in ip format, that correspond the IPs',
  'format': 'subnet',
  'items': {'format': 'subnet', 'type': 'string'},
  'name': 'specific_data.data.network_interfaces.subnets',
  'title': 'Network Interfaces: Subnets',
  'type': 'array'},
 {'description': 'A list of vlans in this interface',
  'items': [{'name': 'name', 'title': 'Vlan Name', 'type': 'string'},
            {'name': 'tagid', 'title': 'Tag ID', 'type': 'integer'},
            {'enum': ['Tagged', 'Untagged'],
             'name': 'tagness',
             'title': 'Vlan Tagness',
             'type': 'string'}],
  'name': 'specific_data.data.network_interfaces.vlan_list',
  'title': 'Network Interfaces: Vlans',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.network_interfaces.vlan_list.name',
  'title': 'Network Interfaces: Vlans: Vlan Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.network_interfaces.vlan_list.tagid',
  'title': 'Network Interfaces: Vlans: Tag ID',
  'type': 'integer'},
 {'branched': True,
  'enum': ['Tagged', 'Untagged'],
  'name': 'specific_data.data.network_interfaces.vlan_list.tagness',
  'title': 'Network Interfaces: Vlans: Vlan Tagness',
  'type': 'string'},
 {'branched': True,
  'enum': ['Up',
           'Down',
           'Testing',
           'Unknown',
           'Dormant',
           'Nonpresent',
           'LowerLayerDown'],
  'name': 'specific_data.data.network_interfaces.operational_status',
  'title': 'Network Interfaces: Operational Status',
  'type': 'string'},
 {'branched': True,
  'enum': ['Up', 'Down'],
  'name': 'specific_data.data.network_interfaces.admin_status',
  'title': 'Network Interfaces: Admin Status',
  'type': 'string'},
 {'branched': True,
  'description': 'Interface max speed per Second',
  'name': 'specific_data.data.network_interfaces.speed',
  'title': 'Network Interfaces: Interface Speed',
  'type': 'string'},
 {'branched': True,
  'enum': ['Access', 'Trunk'],
  'name': 'specific_data.data.network_interfaces.port_type',
  'title': 'Network Interfaces: Port Type',
  'type': 'string'},
 {'branched': True,
  'description': 'Interface Maximum transmission unit',
  'name': 'specific_data.data.network_interfaces.mtu',
  'title': 'Network Interfaces: MTU',
  'type': 'string'},
 {'enum': ['Windows',
           'Linux',
           'OS X',
           'iOS',
           'Android',
           'FreeBSD',
           'VMWare',
           'Cisco',
           'Mikrotik'],
  'name': 'specific_data.data.os.type',
  'title': 'OS: Type',
  'type': 'string'},
 {'name': 'specific_data.data.os.distribution',
  'title': 'OS: Distribution',
  'type': 'string'},
 {'enum': [32, 64],
  'name': 'specific_data.data.os.bitness',
  'title': 'OS: Bitness',
  'type': 'integer'},
 {'name': 'specific_data.data.os.sp',
  'title': 'OS: Service Pack',
  'type': 'string'},
 {'format': 'date-time',
  'name': 'specific_data.data.os.install_date',
  'title': 'OS: Install Date',
  'type': 'string'},
 {'name': 'specific_data.data.os.kernel_version',
  'title': 'OS: Kernel Version',
  'type': 'string'},
 {'name': 'specific_data.data.os.codename',
  'title': 'OS: Code name',
  'type': 'string'},
 {'name': 'specific_data.data.os.major',
  'title': 'OS: Major',
  'type': 'integer'},
 {'name': 'specific_data.data.os.minor',
  'title': 'OS: Minor',
  'type': 'integer'},
 {'name': 'specific_data.data.os.build',
  'title': 'OS: Build',
  'type': 'string'},
 {'items': {'type': 'string'},
  'name': 'specific_data.data.last_used_users',
  'title': 'Last Used User',
  'type': 'array'},
 {'format': 'table',
  'items': [{'name': 'name', 'title': 'Software Name', 'type': 'string'},
            {'name': 'version', 'title': 'Software Version', 'type': 'string'},
            {'enum': ['x86',
                      'x64',
                      'MIPS',
                      'Alpha',
                      'PowerPC',
                      'ARM',
                      'ia64',
                      'all'],
             'name': 'architecture',
             'title': 'Software Architecture',
             'type': 'string'},
            {'name': 'description',
             'title': 'Software Description',
             'type': 'string'},
            {'name': 'vendor', 'title': 'Software Vendor', 'type': 'string'}],
  'name': 'specific_data.data.installed_software',
  'title': 'Installed Software',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.installed_software.name',
  'title': 'Installed Software: Software Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.installed_software.version',
  'title': 'Installed Software: Software Version',
  'type': 'string'},
 {'branched': True,
  'enum': ['x86', 'x64', 'MIPS', 'Alpha', 'PowerPC', 'ARM', 'ia64', 'all'],
  'name': 'specific_data.data.installed_software.architecture',
  'title': 'Installed Software: Software Architecture',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.installed_software.description',
  'title': 'Installed Software: Software Description',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.installed_software.vendor',
  'title': 'Installed Software: Software Vendor',
  'type': 'string'},
 {'format': 'table',
  'items': [{'name': 'software_vendor',
             'title': 'Software Vendor',
             'type': 'string'},
            {'name': 'software_name',
             'title': 'Software Name',
             'type': 'string'},
            {'name': 'software_version',
             'title': 'Software Version',
             'type': 'string'},
            {'name': 'cve_id', 'title': 'CVE ID', 'type': 'string'},
            {'name': 'cve_description',
             'title': 'CVE Description',
             'type': 'string'},
            {'items': {'type': 'string'},
             'name': 'cve_references',
             'title': 'CVE References',
             'type': 'array'},
            {'name': 'cve_severity',
             'title': 'CVE Severity (Metric V3)',
             'type': 'string'}],
  'name': 'specific_data.data.software_cves',
  'title': 'Vulnerable Software',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.software_cves.software_vendor',
  'title': 'Vulnerable Software: Software Vendor',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.software_cves.software_name',
  'title': 'Vulnerable Software: Software Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.software_cves.software_version',
  'title': 'Vulnerable Software: Software Version',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.software_cves.cve_id',
  'title': 'Vulnerable Software: CVE ID',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.software_cves.cve_description',
  'title': 'Vulnerable Software: CVE Description',
  'type': 'string'},
 {'items': {'type': 'string'},
  'name': 'specific_data.data.software_cves.cve_references',
  'title': 'Vulnerable Software: CVE References',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.software_cves.cve_severity',
  'title': 'Vulnerable Software: CVE Severity (Metric V3)',
  'type': 'string'},
 {'format': 'table',
  'items': [{'name': 'security_patch_id',
             'title': 'Security Patch Name',
             'type': 'string'},
            {'name': 'patch_description',
             'title': 'Patch Description',
             'type': 'string'}],
  'name': 'specific_data.data.security_patches',
  'title': 'OS Installed Security Patches',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.security_patches.security_patch_id',
  'title': 'OS Installed Security Patches: Security Patch Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.security_patches.patch_description',
  'title': 'OS Installed Security Patches: Patch Description',
  'type': 'string'},
 {'format': 'table',
  'items': [{'name': 'title', 'title': 'Title', 'type': 'string'},
            {'items': {'type': 'string'},
             'name': 'security_bulletin_ids',
             'title': "Security Bulletin ID's",
             'type': 'array'},
            {'items': {'type': 'string'},
             'name': 'kb_article_ids',
             'title': "KB Article ID's",
             'type': 'array'},
            {'name': 'msrc_severity',
             'title': 'MSRC Severity',
             'type': 'string'},
            {'enum': ['Software', 'Driver'],
             'name': 'patch_type',
             'title': 'Type',
             'type': 'string'},
            {'items': {'type': 'string'},
             'name': 'categories',
             'title': 'Categories',
             'type': 'array'},
            {'format': 'date-time',
             'name': 'publish_date',
             'title': 'Publish Date',
             'type': 'string'}],
  'name': 'specific_data.data.available_security_patches',
  'title': 'OS Available Security Patches',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.available_security_patches.title',
  'title': 'OS Available Security Patches: Title',
  'type': 'string'},
 {'items': {'type': 'string'},
  'name': 'specific_data.data.available_security_patches.security_bulletin_ids',
  'title': "OS Available Security Patches: Security Bulletin ID's",
  'type': 'array'},
 {'items': {'type': 'string'},
  'name': 'specific_data.data.available_security_patches.kb_article_ids',
  'title': "OS Available Security Patches: KB Article ID's",
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.available_security_patches.msrc_severity',
  'title': 'OS Available Security Patches: MSRC Severity',
  'type': 'string'},
 {'branched': True,
  'enum': ['Software', 'Driver'],
  'name': 'specific_data.data.available_security_patches.patch_type',
  'title': 'OS Available Security Patches: Type',
  'type': 'string'},
 {'items': {'type': 'string'},
  'name': 'specific_data.data.available_security_patches.categories',
  'title': 'OS Available Security Patches: Categories',
  'type': 'array'},
 {'branched': True,
  'format': 'date-time',
  'name': 'specific_data.data.available_security_patches.publish_date',
  'title': 'OS Available Security Patches: Publish Date',
  'type': 'string'},
 {'format': 'table',
  'items': [{'name': 'name', 'title': 'Name', 'type': 'string'},
            {'name': 'manufacturer', 'title': 'Manufacturer', 'type': 'string'},
            {'name': 'hw_id', 'title': 'ID', 'type': 'string'}],
  'name': 'specific_data.data.connected_hardware',
  'title': 'Connected Hardware',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.connected_hardware.name',
  'title': 'Connected Hardware: Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.connected_hardware.manufacturer',
  'title': 'Connected Hardware: Manufacturer',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.connected_hardware.hw_id',
  'title': 'Connected Hardware: ID',
  'type': 'string'},
 {'format': 'table',
  'items': [{'name': 'remote_name',
             'title': 'Remote Device Name',
             'type': 'string'},
            {'items': [{'name': 'name',
                        'title': 'Iface Name',
                        'type': 'string'},
                       {'name': 'mac', 'title': 'Mac', 'type': 'string'},
                       {'name': 'manufacturer',
                        'title': 'Manufacturer',
                        'type': 'string'},
                       {'format': 'ip',
                        'items': {'format': 'ip', 'type': 'string'},
                        'name': 'ips',
                        'title': 'IPs',
                        'type': 'array'},
                       {'description': 'A list of subnets in ip format, that '
                                       'correspond the IPs',
                        'format': 'subnet',
                        'items': {'format': 'subnet', 'type': 'string'},
                        'name': 'subnets',
                        'title': 'Subnets',
                        'type': 'array'},
                       {'description': 'A list of vlans in this interface',
                        'items': [{'name': 'name',
                                   'title': 'Vlan Name',
                                   'type': 'string'},
                                  {'name': 'tagid',
                                   'title': 'Tag ID',
                                   'type': 'integer'},
                                  {'enum': ['Tagged', 'Untagged'],
                                   'name': 'tagness',
                                   'title': 'Vlan Tagness',
                                   'type': 'string'}],
                        'name': 'vlan_list',
                        'title': 'Vlans',
                        'type': 'array'},
                       {'branched': True,
                        'name': 'vlan_list.name',
                        'title': 'Vlans: Vlan Name',
                        'type': 'string'},
                       {'branched': True,
                        'name': 'vlan_list.tagid',
                        'title': 'Vlans: Tag ID',
                        'type': 'integer'},
                       {'branched': True,
                        'enum': ['Tagged', 'Untagged'],
                        'name': 'vlan_list.tagness',
                        'title': 'Vlans: Vlan Tagness',
                        'type': 'string'},
                       {'enum': ['Up',
                                 'Down',
                                 'Testing',
                                 'Unknown',
                                 'Dormant',
                                 'Nonpresent',
                                 'LowerLayerDown'],
                        'name': 'operational_status',
                        'title': 'Operational Status',
                        'type': 'string'},
                       {'enum': ['Up', 'Down'],
                        'name': 'admin_status',
                        'title': 'Admin Status',
                        'type': 'string'},
                       {'description': 'Interface max speed per Second',
                        'name': 'speed',
                        'title': 'Interface Speed',
                        'type': 'string'},
                       {'enum': ['Access', 'Trunk'],
                        'name': 'port_type',
                        'title': 'Port Type',
                        'type': 'string'},
                       {'description': 'Interface Maximum transmission unit',
                        'name': 'mtu',
                        'title': 'MTU',
                        'type': 'string'}],
             'name': 'local_ifaces',
             'title': 'Local Interface',
             'type': 'array'},
            {'branched': True,
             'name': 'local_ifaces.name',
             'title': 'Local Interface: Iface Name',
             'type': 'string'},
            {'branched': True,
             'name': 'local_ifaces.mac',
             'title': 'Local Interface: Mac',
             'type': 'string'},
            {'branched': True,
             'name': 'local_ifaces.manufacturer',
             'title': 'Local Interface: Manufacturer',
             'type': 'string'},
            {'format': 'ip',
             'items': {'format': 'ip', 'type': 'string'},
             'name': 'local_ifaces.ips',
             'title': 'Local Interface: IPs',
             'type': 'array'},
            {'description': 'A list of subnets in ip format, that correspond '
                            'the IPs',
             'format': 'subnet',
             'items': {'format': 'subnet', 'type': 'string'},
             'name': 'local_ifaces.subnets',
             'title': 'Local Interface: Subnets',
             'type': 'array'},
            {'description': 'A list of vlans in this interface',
             'items': [{'name': 'name', 'title': 'Vlan Name', 'type': 'string'},
                       {'name': 'tagid', 'title': 'Tag ID', 'type': 'integer'},
                       {'enum': ['Tagged', 'Untagged'],
                        'name': 'tagness',
                        'title': 'Vlan Tagness',
                        'type': 'string'}],
             'name': 'local_ifaces.vlan_list',
             'title': 'Local Interface: Vlans',
             'type': 'array'},
            {'branched': True,
             'name': 'local_ifaces.vlan_list.name',
             'title': 'Local Interface: Vlans: Vlan Name',
             'type': 'string'},
            {'branched': True,
             'name': 'local_ifaces.vlan_list.tagid',
             'title': 'Local Interface: Vlans: Tag ID',
             'type': 'integer'},
            {'branched': True,
             'enum': ['Tagged', 'Untagged'],
             'name': 'local_ifaces.vlan_list.tagness',
             'title': 'Local Interface: Vlans: Vlan Tagness',
             'type': 'string'},
            {'branched': True,
             'enum': ['Up',
                      'Down',
                      'Testing',
                      'Unknown',
                      'Dormant',
                      'Nonpresent',
                      'LowerLayerDown'],
             'name': 'local_ifaces.operational_status',
             'title': 'Local Interface: Operational Status',
             'type': 'string'},
            {'branched': True,
             'enum': ['Up', 'Down'],
             'name': 'local_ifaces.admin_status',
             'title': 'Local Interface: Admin Status',
             'type': 'string'},
            {'branched': True,
             'description': 'Interface max speed per Second',
             'name': 'local_ifaces.speed',
             'title': 'Local Interface: Interface Speed',
             'type': 'string'},
            {'branched': True,
             'enum': ['Access', 'Trunk'],
             'name': 'local_ifaces.port_type',
             'title': 'Local Interface: Port Type',
             'type': 'string'},
            {'branched': True,
             'description': 'Interface Maximum transmission unit',
             'name': 'local_ifaces.mtu',
             'title': 'Local Interface: MTU',
             'type': 'string'},
            {'items': [{'name': 'name',
                        'title': 'Iface Name',
                        'type': 'string'},
                       {'name': 'mac', 'title': 'Mac', 'type': 'string'},
                       {'name': 'manufacturer',
                        'title': 'Manufacturer',
                        'type': 'string'},
                       {'format': 'ip',
                        'items': {'format': 'ip', 'type': 'string'},
                        'name': 'ips',
                        'title': 'IPs',
                        'type': 'array'},
                       {'description': 'A list of subnets in ip format, that '
                                       'correspond the IPs',
                        'format': 'subnet',
                        'items': {'format': 'subnet', 'type': 'string'},
                        'name': 'subnets',
                        'title': 'Subnets',
                        'type': 'array'},
                       {'description': 'A list of vlans in this interface',
                        'items': [{'name': 'name',
                                   'title': 'Vlan Name',
                                   'type': 'string'},
                                  {'name': 'tagid',
                                   'title': 'Tag ID',
                                   'type': 'integer'},
                                  {'enum': ['Tagged', 'Untagged'],
                                   'name': 'tagness',
                                   'title': 'Vlan Tagness',
                                   'type': 'string'}],
                        'name': 'vlan_list',
                        'title': 'Vlans',
                        'type': 'array'},
                       {'branched': True,
                        'name': 'vlan_list.name',
                        'title': 'Vlans: Vlan Name',
                        'type': 'string'},
                       {'branched': True,
                        'name': 'vlan_list.tagid',
                        'title': 'Vlans: Tag ID',
                        'type': 'integer'},
                       {'branched': True,
                        'enum': ['Tagged', 'Untagged'],
                        'name': 'vlan_list.tagness',
                        'title': 'Vlans: Vlan Tagness',
                        'type': 'string'},
                       {'enum': ['Up',
                                 'Down',
                                 'Testing',
                                 'Unknown',
                                 'Dormant',
                                 'Nonpresent',
                                 'LowerLayerDown'],
                        'name': 'operational_status',
                        'title': 'Operational Status',
                        'type': 'string'},
                       {'enum': ['Up', 'Down'],
                        'name': 'admin_status',
                        'title': 'Admin Status',
                        'type': 'string'},
                       {'description': 'Interface max speed per Second',
                        'name': 'speed',
                        'title': 'Interface Speed',
                        'type': 'string'},
                       {'enum': ['Access', 'Trunk'],
                        'name': 'port_type',
                        'title': 'Port Type',
                        'type': 'string'},
                       {'description': 'Interface Maximum transmission unit',
                        'name': 'mtu',
                        'title': 'MTU',
                        'type': 'string'}],
             'name': 'remote_ifaces',
             'title': 'Remote Device Iface',
             'type': 'array'},
            {'branched': True,
             'name': 'remote_ifaces.name',
             'title': 'Remote Device Iface: Iface Name',
             'type': 'string'},
            {'branched': True,
             'name': 'remote_ifaces.mac',
             'title': 'Remote Device Iface: Mac',
             'type': 'string'},
            {'branched': True,
             'name': 'remote_ifaces.manufacturer',
             'title': 'Remote Device Iface: Manufacturer',
             'type': 'string'},
            {'format': 'ip',
             'items': {'format': 'ip', 'type': 'string'},
             'name': 'remote_ifaces.ips',
             'title': 'Remote Device Iface: IPs',
             'type': 'array'},
            {'description': 'A list of subnets in ip format, that correspond '
                            'the IPs',
             'format': 'subnet',
             'items': {'format': 'subnet', 'type': 'string'},
             'name': 'remote_ifaces.subnets',
             'title': 'Remote Device Iface: Subnets',
             'type': 'array'},
            {'description': 'A list of vlans in this interface',
             'items': [{'name': 'name', 'title': 'Vlan Name', 'type': 'string'},
                       {'name': 'tagid', 'title': 'Tag ID', 'type': 'integer'},
                       {'enum': ['Tagged', 'Untagged'],
                        'name': 'tagness',
                        'title': 'Vlan Tagness',
                        'type': 'string'}],
             'name': 'remote_ifaces.vlan_list',
             'title': 'Remote Device Iface: Vlans',
             'type': 'array'},
            {'branched': True,
             'name': 'remote_ifaces.vlan_list.name',
             'title': 'Remote Device Iface: Vlans: Vlan Name',
             'type': 'string'},
            {'branched': True,
             'name': 'remote_ifaces.vlan_list.tagid',
             'title': 'Remote Device Iface: Vlans: Tag ID',
             'type': 'integer'},
            {'branched': True,
             'enum': ['Tagged', 'Untagged'],
             'name': 'remote_ifaces.vlan_list.tagness',
             'title': 'Remote Device Iface: Vlans: Vlan Tagness',
             'type': 'string'},
            {'branched': True,
             'enum': ['Up',
                      'Down',
                      'Testing',
                      'Unknown',
                      'Dormant',
                      'Nonpresent',
                      'LowerLayerDown'],
             'name': 'remote_ifaces.operational_status',
             'title': 'Remote Device Iface: Operational Status',
             'type': 'string'},
            {'branched': True,
             'enum': ['Up', 'Down'],
             'name': 'remote_ifaces.admin_status',
             'title': 'Remote Device Iface: Admin Status',
             'type': 'string'},
            {'branched': True,
             'description': 'Interface max speed per Second',
             'name': 'remote_ifaces.speed',
             'title': 'Remote Device Iface: Interface Speed',
             'type': 'string'},
            {'branched': True,
             'enum': ['Access', 'Trunk'],
             'name': 'remote_ifaces.port_type',
             'title': 'Remote Device Iface: Port Type',
             'type': 'string'},
            {'branched': True,
             'description': 'Interface Maximum transmission unit',
             'name': 'remote_ifaces.mtu',
             'title': 'Remote Device Iface: MTU',
             'type': 'string'},
            {'enum': ['Direct', 'Indirect'],
             'name': 'connection_type',
             'title': 'Connection Type',
             'type': 'string'}],
  'name': 'specific_data.data.connected_devices',
  'title': 'Connected Devices',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.connected_devices.remote_name',
  'title': 'Connected Devices: Remote Device Name',
  'type': 'string'},
 {'items': [{'name': 'name', 'title': 'Iface Name', 'type': 'string'},
            {'name': 'mac', 'title': 'Mac', 'type': 'string'},
            {'name': 'manufacturer', 'title': 'Manufacturer', 'type': 'string'},
            {'format': 'ip',
             'items': {'format': 'ip', 'type': 'string'},
             'name': 'ips',
             'title': 'IPs',
             'type': 'array'},
            {'description': 'A list of subnets in ip format, that correspond '
                            'the IPs',
             'format': 'subnet',
             'items': {'format': 'subnet', 'type': 'string'},
             'name': 'subnets',
             'title': 'Subnets',
             'type': 'array'},
            {'description': 'A list of vlans in this interface',
             'items': [{'name': 'name', 'title': 'Vlan Name', 'type': 'string'},
                       {'name': 'tagid', 'title': 'Tag ID', 'type': 'integer'},
                       {'enum': ['Tagged', 'Untagged'],
                        'name': 'tagness',
                        'title': 'Vlan Tagness',
                        'type': 'string'}],
             'name': 'vlan_list',
             'title': 'Vlans',
             'type': 'array'},
            {'branched': True,
             'name': 'vlan_list.name',
             'title': 'Vlans: Vlan Name',
             'type': 'string'},
            {'branched': True,
             'name': 'vlan_list.tagid',
             'title': 'Vlans: Tag ID',
             'type': 'integer'},
            {'branched': True,
             'enum': ['Tagged', 'Untagged'],
             'name': 'vlan_list.tagness',
             'title': 'Vlans: Vlan Tagness',
             'type': 'string'},
            {'enum': ['Up',
                      'Down',
                      'Testing',
                      'Unknown',
                      'Dormant',
                      'Nonpresent',
                      'LowerLayerDown'],
             'name': 'operational_status',
             'title': 'Operational Status',
             'type': 'string'},
            {'enum': ['Up', 'Down'],
             'name': 'admin_status',
             'title': 'Admin Status',
             'type': 'string'},
            {'description': 'Interface max speed per Second',
             'name': 'speed',
             'title': 'Interface Speed',
             'type': 'string'},
            {'enum': ['Access', 'Trunk'],
             'name': 'port_type',
             'title': 'Port Type',
             'type': 'string'},
            {'description': 'Interface Maximum transmission unit',
             'name': 'mtu',
             'title': 'MTU',
             'type': 'string'}],
  'name': 'specific_data.data.connected_devices.local_ifaces',
  'title': 'Connected Devices: Local Interface',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.connected_devices.local_ifaces.name',
  'title': 'Connected Devices: Local Interface: Iface Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.connected_devices.local_ifaces.mac',
  'title': 'Connected Devices: Local Interface: Mac',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.connected_devices.local_ifaces.manufacturer',
  'title': 'Connected Devices: Local Interface: Manufacturer',
  'type': 'string'},
 {'format': 'ip',
  'items': {'format': 'ip', 'type': 'string'},
  'name': 'specific_data.data.connected_devices.local_ifaces.ips',
  'title': 'Connected Devices: Local Interface: IPs',
  'type': 'array'},
 {'description': 'A list of subnets in ip format, that correspond the IPs',
  'format': 'subnet',
  'items': {'format': 'subnet', 'type': 'string'},
  'name': 'specific_data.data.connected_devices.local_ifaces.subnets',
  'title': 'Connected Devices: Local Interface: Subnets',
  'type': 'array'},
 {'description': 'A list of vlans in this interface',
  'items': [{'name': 'name', 'title': 'Vlan Name', 'type': 'string'},
            {'name': 'tagid', 'title': 'Tag ID', 'type': 'integer'},
            {'enum': ['Tagged', 'Untagged'],
             'name': 'tagness',
             'title': 'Vlan Tagness',
             'type': 'string'}],
  'name': 'specific_data.data.connected_devices.local_ifaces.vlan_list',
  'title': 'Connected Devices: Local Interface: Vlans',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.connected_devices.local_ifaces.vlan_list.name',
  'title': 'Connected Devices: Local Interface: Vlans: Vlan Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.connected_devices.local_ifaces.vlan_list.tagid',
  'title': 'Connected Devices: Local Interface: Vlans: Tag ID',
  'type': 'integer'},
 {'branched': True,
  'enum': ['Tagged', 'Untagged'],
  'name': 'specific_data.data.connected_devices.local_ifaces.vlan_list.tagness',
  'title': 'Connected Devices: Local Interface: Vlans: Vlan Tagness',
  'type': 'string'},
 {'branched': True,
  'enum': ['Up',
           'Down',
           'Testing',
           'Unknown',
           'Dormant',
           'Nonpresent',
           'LowerLayerDown'],
  'name': 'specific_data.data.connected_devices.local_ifaces.operational_status',
  'title': 'Connected Devices: Local Interface: Operational Status',
  'type': 'string'},
 {'branched': True,
  'enum': ['Up', 'Down'],
  'name': 'specific_data.data.connected_devices.local_ifaces.admin_status',
  'title': 'Connected Devices: Local Interface: Admin Status',
  'type': 'string'},
 {'branched': True,
  'description': 'Interface max speed per Second',
  'name': 'specific_data.data.connected_devices.local_ifaces.speed',
  'title': 'Connected Devices: Local Interface: Interface Speed',
  'type': 'string'},
 {'branched': True,
  'enum': ['Access', 'Trunk'],
  'name': 'specific_data.data.connected_devices.local_ifaces.port_type',
  'title': 'Connected Devices: Local Interface: Port Type',
  'type': 'string'},
 {'branched': True,
  'description': 'Interface Maximum transmission unit',
  'name': 'specific_data.data.connected_devices.local_ifaces.mtu',
  'title': 'Connected Devices: Local Interface: MTU',
  'type': 'string'},
 {'items': [{'name': 'name', 'title': 'Iface Name', 'type': 'string'},
            {'name': 'mac', 'title': 'Mac', 'type': 'string'},
            {'name': 'manufacturer', 'title': 'Manufacturer', 'type': 'string'},
            {'format': 'ip',
             'items': {'format': 'ip', 'type': 'string'},
             'name': 'ips',
             'title': 'IPs',
             'type': 'array'},
            {'description': 'A list of subnets in ip format, that correspond '
                            'the IPs',
             'format': 'subnet',
             'items': {'format': 'subnet', 'type': 'string'},
             'name': 'subnets',
             'title': 'Subnets',
             'type': 'array'},
            {'description': 'A list of vlans in this interface',
             'items': [{'name': 'name', 'title': 'Vlan Name', 'type': 'string'},
                       {'name': 'tagid', 'title': 'Tag ID', 'type': 'integer'},
                       {'enum': ['Tagged', 'Untagged'],
                        'name': 'tagness',
                        'title': 'Vlan Tagness',
                        'type': 'string'}],
             'name': 'vlan_list',
             'title': 'Vlans',
             'type': 'array'},
            {'branched': True,
             'name': 'vlan_list.name',
             'title': 'Vlans: Vlan Name',
             'type': 'string'},
            {'branched': True,
             'name': 'vlan_list.tagid',
             'title': 'Vlans: Tag ID',
             'type': 'integer'},
            {'branched': True,
             'enum': ['Tagged', 'Untagged'],
             'name': 'vlan_list.tagness',
             'title': 'Vlans: Vlan Tagness',
             'type': 'string'},
            {'enum': ['Up',
                      'Down',
                      'Testing',
                      'Unknown',
                      'Dormant',
                      'Nonpresent',
                      'LowerLayerDown'],
             'name': 'operational_status',
             'title': 'Operational Status',
             'type': 'string'},
            {'enum': ['Up', 'Down'],
             'name': 'admin_status',
             'title': 'Admin Status',
             'type': 'string'},
            {'description': 'Interface max speed per Second',
             'name': 'speed',
             'title': 'Interface Speed',
             'type': 'string'},
            {'enum': ['Access', 'Trunk'],
             'name': 'port_type',
             'title': 'Port Type',
             'type': 'string'},
            {'description': 'Interface Maximum transmission unit',
             'name': 'mtu',
             'title': 'MTU',
             'type': 'string'}],
  'name': 'specific_data.data.connected_devices.remote_ifaces',
  'title': 'Connected Devices: Remote Device Iface',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.connected_devices.remote_ifaces.name',
  'title': 'Connected Devices: Remote Device Iface: Iface Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.connected_devices.remote_ifaces.mac',
  'title': 'Connected Devices: Remote Device Iface: Mac',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.connected_devices.remote_ifaces.manufacturer',
  'title': 'Connected Devices: Remote Device Iface: Manufacturer',
  'type': 'string'},
 {'format': 'ip',
  'items': {'format': 'ip', 'type': 'string'},
  'name': 'specific_data.data.connected_devices.remote_ifaces.ips',
  'title': 'Connected Devices: Remote Device Iface: IPs',
  'type': 'array'},
 {'description': 'A list of subnets in ip format, that correspond the IPs',
  'format': 'subnet',
  'items': {'format': 'subnet', 'type': 'string'},
  'name': 'specific_data.data.connected_devices.remote_ifaces.subnets',
  'title': 'Connected Devices: Remote Device Iface: Subnets',
  'type': 'array'},
 {'description': 'A list of vlans in this interface',
  'items': [{'name': 'name', 'title': 'Vlan Name', 'type': 'string'},
            {'name': 'tagid', 'title': 'Tag ID', 'type': 'integer'},
            {'enum': ['Tagged', 'Untagged'],
             'name': 'tagness',
             'title': 'Vlan Tagness',
             'type': 'string'}],
  'name': 'specific_data.data.connected_devices.remote_ifaces.vlan_list',
  'title': 'Connected Devices: Remote Device Iface: Vlans',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.connected_devices.remote_ifaces.vlan_list.name',
  'title': 'Connected Devices: Remote Device Iface: Vlans: Vlan Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.connected_devices.remote_ifaces.vlan_list.tagid',
  'title': 'Connected Devices: Remote Device Iface: Vlans: Tag ID',
  'type': 'integer'},
 {'branched': True,
  'enum': ['Tagged', 'Untagged'],
  'name': 'specific_data.data.connected_devices.remote_ifaces.vlan_list.tagness',
  'title': 'Connected Devices: Remote Device Iface: Vlans: Vlan Tagness',
  'type': 'string'},
 {'branched': True,
  'enum': ['Up',
           'Down',
           'Testing',
           'Unknown',
           'Dormant',
           'Nonpresent',
           'LowerLayerDown'],
  'name': 'specific_data.data.connected_devices.remote_ifaces.operational_status',
  'title': 'Connected Devices: Remote Device Iface: Operational Status',
  'type': 'string'},
 {'branched': True,
  'enum': ['Up', 'Down'],
  'name': 'specific_data.data.connected_devices.remote_ifaces.admin_status',
  'title': 'Connected Devices: Remote Device Iface: Admin Status',
  'type': 'string'},
 {'branched': True,
  'description': 'Interface max speed per Second',
  'name': 'specific_data.data.connected_devices.remote_ifaces.speed',
  'title': 'Connected Devices: Remote Device Iface: Interface Speed',
  'type': 'string'},
 {'branched': True,
  'enum': ['Access', 'Trunk'],
  'name': 'specific_data.data.connected_devices.remote_ifaces.port_type',
  'title': 'Connected Devices: Remote Device Iface: Port Type',
  'type': 'string'},
 {'branched': True,
  'description': 'Interface Maximum transmission unit',
  'name': 'specific_data.data.connected_devices.remote_ifaces.mtu',
  'title': 'Connected Devices: Remote Device Iface: MTU',
  'type': 'string'},
 {'branched': True,
  'enum': ['Direct', 'Indirect'],
  'name': 'specific_data.data.connected_devices.connection_type',
  'title': 'Connected Devices: Connection Type',
  'type': 'string'},
 {'name': 'specific_data.data.id', 'title': 'ID', 'type': 'string'},
 {'name': 'specific_data.data.part_of_domain',
  'title': 'Part Of Domain',
  'type': 'bool'},
 {'name': 'specific_data.data.domain', 'title': 'Domain', 'type': 'string'},
 {'format': 'table',
  'items': [{'name': 'user_sid', 'title': 'SID', 'type': 'string'},
            {'name': 'username', 'title': 'Username', 'type': 'string'},
            {'format': 'date-time',
             'name': 'last_use_date',
             'title': 'Last Use Time',
             'type': 'string'},
            {'name': 'is_local', 'title': 'Is Local', 'type': 'bool'},
            {'name': 'is_disabled', 'title': 'Is Disabled', 'type': 'bool'},
            {'name': 'is_admin', 'title': 'Is Admin', 'type': 'bool'},
            {'name': 'user_department',
             'title': 'Department',
             'type': 'string'},
            {'name': 'password_max_age',
             'title': 'Password Max Age',
             'type': 'integer'},
            {'name': 'interpreter', 'title': 'Interpreter', 'type': 'string'}],
  'name': 'specific_data.data.users',
  'title': 'Users',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.users.user_sid',
  'title': 'Users: SID',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.users.username',
  'title': 'Users: Username',
  'type': 'string'},
 {'branched': True,
  'format': 'date-time',
  'name': 'specific_data.data.users.last_use_date',
  'title': 'Users: Last Use Time',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.users.is_local',
  'title': 'Users: Is Local',
  'type': 'bool'},
 {'branched': True,
  'name': 'specific_data.data.users.is_disabled',
  'title': 'Users: Is Disabled',
  'type': 'bool'},
 {'branched': True,
  'name': 'specific_data.data.users.is_admin',
  'title': 'Users: Is Admin',
  'type': 'bool'},
 {'branched': True,
  'name': 'specific_data.data.users.user_department',
  'title': 'Users: Department',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.users.password_max_age',
  'title': 'Users: Password Max Age',
  'type': 'integer'},
 {'branched': True,
  'name': 'specific_data.data.users.interpreter',
  'title': 'Users: Interpreter',
  'type': 'string'},
 {'format': 'table',
  'items': [{'name': 'admin_name',
             'title': 'Name of user or group',
             'type': 'string'},
            {'enum': ['Group Membership', 'Admin User'],
             'name': 'admin_type',
             'title': 'Admin Type',
             'type': 'string'}],
  'name': 'specific_data.data.local_admins',
  'title': 'Local Admins',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.local_admins.admin_name',
  'title': 'Local Admins: Name of user or group',
  'type': 'string'},
 {'branched': True,
  'enum': ['Group Membership', 'Admin User'],
  'name': 'specific_data.data.local_admins.admin_type',
  'title': 'Local Admins: Admin Type',
  'type': 'string'},
 {'name': 'specific_data.data.pretty_id',
  'title': 'Axonius Name',
  'type': 'string'},
 {'name': 'specific_data.data.related_ips.name',
  'title': 'Related Ips: Iface Name',
  'type': 'string'},
 {'name': 'specific_data.data.related_ips.mac',
  'title': 'Related Ips: Mac',
  'type': 'string'},
 {'name': 'specific_data.data.related_ips.manufacturer',
  'title': 'Related Ips: Manufacturer',
  'type': 'string'},
 {'format': 'ip',
  'items': {'format': 'ip', 'type': 'string'},
  'name': 'specific_data.data.related_ips.ips',
  'title': 'Related Ips: IPs',
  'type': 'array'},
 {'description': 'A list of subnets in ip format, that correspond the IPs',
  'format': 'subnet',
  'items': {'format': 'subnet', 'type': 'string'},
  'name': 'specific_data.data.related_ips.subnets',
  'title': 'Related Ips: Subnets',
  'type': 'array'},
 {'description': 'A list of vlans in this interface',
  'items': [{'name': 'name', 'title': 'Vlan Name', 'type': 'string'},
            {'name': 'tagid', 'title': 'Tag ID', 'type': 'integer'},
            {'enum': ['Tagged', 'Untagged'],
             'name': 'tagness',
             'title': 'Vlan Tagness',
             'type': 'string'}],
  'name': 'specific_data.data.related_ips.vlan_list',
  'title': 'Related Ips: Vlans',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.related_ips.vlan_list.name',
  'title': 'Related Ips: Vlans: Vlan Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.related_ips.vlan_list.tagid',
  'title': 'Related Ips: Vlans: Tag ID',
  'type': 'integer'},
 {'branched': True,
  'enum': ['Tagged', 'Untagged'],
  'name': 'specific_data.data.related_ips.vlan_list.tagness',
  'title': 'Related Ips: Vlans: Vlan Tagness',
  'type': 'string'},
 {'enum': ['Up',
           'Down',
           'Testing',
           'Unknown',
           'Dormant',
           'Nonpresent',
           'LowerLayerDown'],
  'name': 'specific_data.data.related_ips.operational_status',
  'title': 'Related Ips: Operational Status',
  'type': 'string'},
 {'enum': ['Up', 'Down'],
  'name': 'specific_data.data.related_ips.admin_status',
  'title': 'Related Ips: Admin Status',
  'type': 'string'},
 {'description': 'Interface max speed per Second',
  'name': 'specific_data.data.related_ips.speed',
  'title': 'Related Ips: Interface Speed',
  'type': 'string'},
 {'enum': ['Access', 'Trunk'],
  'name': 'specific_data.data.related_ips.port_type',
  'title': 'Related Ips: Port Type',
  'type': 'string'},
 {'description': 'Interface Maximum transmission unit',
  'name': 'specific_data.data.related_ips.mtu',
  'title': 'Related Ips: MTU',
  'type': 'string'},
 {'enum': ['Unspecified',
           'Desktop',
           'Laptop or Tablet',
           'Workstation',
           'Enterprise Server',
           'SOHO Server',
           'Appliance PC',
           'Performance Server',
           'Maximum',
           'Mobile'],
  'name': 'specific_data.data.pc_type',
  'title': 'PC Type',
  'type': 'string'},
 {'name': 'specific_data.data.physical_location',
  'title': 'Physical Location',
  'type': 'string'},
 {'name': 'specific_data.data.number_of_processes',
  'title': 'Number Of Processes',
  'type': 'integer'},
 {'format': 'table',
  'items': [{'name': 'path', 'title': 'Path', 'type': 'string'},
            {'name': 'device', 'title': 'Device Name', 'type': 'string'},
            {'name': 'file_system', 'title': 'Filesystem', 'type': 'string'},
            {'name': 'total_size', 'title': 'Size (GB)', 'type': 'number'},
            {'name': 'free_size', 'title': 'Free Size (GB)', 'type': 'number'},
            {'name': 'is_encrypted', 'title': 'Encrypted', 'type': 'bool'},
            {'name': 'description', 'title': 'Description', 'type': 'string'}],
  'name': 'specific_data.data.hard_drives',
  'title': 'Hard Drives',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.hard_drives.path',
  'title': 'Hard Drives: Path',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.hard_drives.device',
  'title': 'Hard Drives: Device Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.hard_drives.file_system',
  'title': 'Hard Drives: Filesystem',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.hard_drives.total_size',
  'title': 'Hard Drives: Size (GB)',
  'type': 'number'},
 {'branched': True,
  'name': 'specific_data.data.hard_drives.free_size',
  'title': 'Hard Drives: Free Size (GB)',
  'type': 'number'},
 {'branched': True,
  'name': 'specific_data.data.hard_drives.is_encrypted',
  'title': 'Hard Drives: Encrypted',
  'type': 'bool'},
 {'branched': True,
  'name': 'specific_data.data.hard_drives.description',
  'title': 'Hard Drives: Description',
  'type': 'string'},
 {'items': [{'name': 'name', 'title': 'Description', 'type': 'string'},
            {'name': 'manufacturer', 'title': 'Manufacturer', 'type': 'string'},
            {'enum': [32, 64],
             'name': 'bitness',
             'title': 'Bitness',
             'type': 'integer'},
            {'name': 'family', 'title': 'Family', 'type': 'string'},
            {'name': 'cores', 'title': 'Cores', 'type': 'integer'},
            {'name': 'cores_thread',
             'title': 'Threads in core',
             'type': 'integer'},
            {'name': 'load_percentage',
             'title': 'Load Percentage',
             'type': 'integer'},
            {'enum': ['x86', 'x64', 'MIPS', 'Alpha', 'PowerPC', 'ARM', 'ia64'],
             'name': 'architecture',
             'title': 'Architecture',
             'type': 'string'},
            {'name': 'ghz', 'title': 'Clockspeed (GHZ)', 'type': 'number'}],
  'name': 'specific_data.data.cpus',
  'title': 'CPUs',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.cpus.name',
  'title': 'CPUs: Description',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.cpus.manufacturer',
  'title': 'CPUs: Manufacturer',
  'type': 'string'},
 {'branched': True,
  'enum': [32, 64],
  'name': 'specific_data.data.cpus.bitness',
  'title': 'CPUs: Bitness',
  'type': 'integer'},
 {'branched': True,
  'name': 'specific_data.data.cpus.family',
  'title': 'CPUs: Family',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.cpus.cores',
  'title': 'CPUs: Cores',
  'type': 'integer'},
 {'branched': True,
  'name': 'specific_data.data.cpus.cores_thread',
  'title': 'CPUs: Threads in core',
  'type': 'integer'},
 {'branched': True,
  'name': 'specific_data.data.cpus.load_percentage',
  'title': 'CPUs: Load Percentage',
  'type': 'integer'},
 {'branched': True,
  'enum': ['x86', 'x64', 'MIPS', 'Alpha', 'PowerPC', 'ARM', 'ia64'],
  'name': 'specific_data.data.cpus.architecture',
  'title': 'CPUs: Architecture',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.cpus.ghz',
  'title': 'CPUs: Clockspeed (GHZ)',
  'type': 'number'},
 {'format': 'date-time',
  'name': 'specific_data.data.boot_time',
  'title': 'Boot Time',
  'type': 'string'},
 {'name': 'specific_data.data.time_zone',
  'title': 'Time Zone',
  'type': 'string'},
 {'name': 'specific_data.data.device_manufacturer',
  'title': 'Device Manufacturer',
  'type': 'string'},
 {'name': 'specific_data.data.device_model',
  'title': 'Device Model',
  'type': 'string'},
 {'name': 'specific_data.data.device_model_family',
  'title': 'Device Model Family',
  'type': 'string'},
 {'name': 'specific_data.data.device_serial',
  'title': 'Device Manufacturer Serial',
  'type': 'string'},
 {'name': 'specific_data.data.bios_version',
  'title': 'Bios Version',
  'type': 'string'},
 {'name': 'specific_data.data.bios_serial',
  'title': 'Bios Serial',
  'type': 'string'},
 {'name': 'specific_data.data.motherboard_manufacturer',
  'title': 'Motherboard Manufacturer',
  'type': 'string'},
 {'name': 'specific_data.data.motherboard_serial',
  'title': 'Motherboard serial',
  'type': 'string'},
 {'name': 'specific_data.data.motherboard_model',
  'title': 'Motherboard Model',
  'type': 'string'},
 {'name': 'specific_data.data.motherboard_version',
  'title': 'Motherboard Version',
  'type': 'string'},
 {'name': 'specific_data.data.total_physical_memory',
  'title': 'Total RAM (GB)',
  'type': 'number'},
 {'name': 'specific_data.data.free_physical_memory',
  'title': 'Free RAM (GB)',
  'type': 'number'},
 {'name': 'specific_data.data.physical_memory_percentage',
  'title': 'RAM Usage (%)',
  'type': 'number'},
 {'items': [{'name': 'name', 'title': 'Name', 'type': 'string'},
            {'name': 'size_in_gb', 'title': 'Size (GB)', 'type': 'integer'}],
  'name': 'specific_data.data.swap_files',
  'title': 'Swap Files',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.swap_files.name',
  'title': 'Swap Files: Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.swap_files.size_in_gb',
  'title': 'Swap Files: Size (GB)',
  'type': 'integer'},
 {'name': 'specific_data.data.swap_total',
  'title': 'Total Swap GB',
  'type': 'number'},
 {'name': 'specific_data.data.swap_cached',
  'title': 'Cached Swap GB',
  'type': 'number'},
 {'name': 'specific_data.data.swap_free',
  'title': 'Free Swap GB',
  'type': 'number'},
 {'name': 'specific_data.data.total_number_of_physical_processors',
  'title': 'Total Physical Processors',
  'type': 'integer'},
 {'name': 'specific_data.data.total_number_of_cores',
  'title': 'Total Cores',
  'type': 'integer'},
 {'items': [{'name': 'percentage', 'title': 'Percentage', 'type': 'integer'},
            {'enum': ['Not Charging',
                      'Connected to AC',
                      'Fully Charged',
                      'Low',
                      'Critical',
                      'Charging',
                      'Charging and High',
                      'Charging and Low',
                      'Charging and Critical',
                      'Undefined',
                      'Partially Charged'],
             'name': 'status',
             'title': 'Status',
             'type': 'string'},
            {'name': 'manufacturer', 'title': 'Manufacturer', 'type': 'string'},
            {'name': 'model', 'title': 'Model', 'type': 'string'},
            {'name': 'capacity', 'title': 'Capacity (mWh)', 'type': 'string'}],
  'name': 'specific_data.data.batteries',
  'title': 'Battery',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.batteries.percentage',
  'title': 'Battery: Percentage',
  'type': 'integer'},
 {'branched': True,
  'enum': ['Not Charging',
           'Connected to AC',
           'Fully Charged',
           'Low',
           'Critical',
           'Charging',
           'Charging and High',
           'Charging and Low',
           'Charging and Critical',
           'Undefined',
           'Partially Charged'],
  'name': 'specific_data.data.batteries.status',
  'title': 'Battery: Status',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.batteries.manufacturer',
  'title': 'Battery: Manufacturer',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.batteries.model',
  'title': 'Battery: Model',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.batteries.capacity',
  'title': 'Battery: Capacity (mWh)',
  'type': 'string'},
 {'name': 'specific_data.data.current_logged_user',
  'title': 'Currently Logged User',
  'type': 'string'},
 {'name': 'specific_data.data.device_disabled',
  'title': 'Device Disabled',
  'type': 'bool'},
 {'enum': ['TurnedOn',
           'TurnedOff',
           'Suspended',
           'ShuttingDown',
           'Rebooting',
           'StartingUp',
           'Normal',
           'Unknown',
           'Error',
           'Migrating'],
  'name': 'specific_data.data.power_state',
  'title': 'Power State',
  'type': 'string'},
 {'name': 'specific_data.data.device_managed_by',
  'title': 'Managed By',
  'type': 'string'},
 {'items': {'type': 'string'},
  'name': 'specific_data.data.organizational_unit',
  'title': 'Organizational Unit',
  'type': 'array'},
 {'format': 'date-time',
  'name': 'specific_data.data.security_patch_level',
  'title': 'Security Patch Level',
  'type': 'string'},
 {'items': [{'name': 'tag_key', 'title': 'Tag Key', 'type': 'string'},
            {'name': 'tag_value', 'title': 'Tag Value', 'type': 'string'}],
  'name': 'specific_data.data.tags',
  'title': 'Tags',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.tags.tag_key',
  'title': 'Tags: Tag Key',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.tags.tag_value',
  'title': 'Tags: Tag Value',
  'type': 'string'},
 {'name': 'specific_data.data.cloud_provider',
  'title': 'Cloud Provider',
  'type': 'string'},
 {'name': 'specific_data.data.cloud_id', 'title': 'Cloud ID', 'type': 'string'},
 {'name': 'specific_data.data.shodan_data.city',
  'title': 'Shodan Data: City',
  'type': 'string'},
 {'name': 'specific_data.data.shodan_data.region_code',
  'title': 'Shodan Data: Region Code',
  'type': 'string'},
 {'name': 'specific_data.data.shodan_data.country_name',
  'title': 'Shodan Data: Country Name',
  'type': 'string'},
 {'name': 'specific_data.data.shodan_data.org',
  'title': 'Shodan Data: Organization',
  'type': 'string'},
 {'name': 'specific_data.data.shodan_data.os',
  'title': 'Shodan Data: OS',
  'type': 'string'},
 {'name': 'specific_data.data.shodan_data.isp',
  'title': 'Shodan Data: ISP',
  'type': 'string'},
 {'items': {'type': 'integer'},
  'name': 'specific_data.data.shodan_data.ports',
  'title': 'Shodan Data: Ports',
  'type': 'array'},
 {'items': [{'name': 'vuln_name',
             'title': 'Vulnerability Name',
             'type': 'string'},
            {'name': 'cvss', 'title': 'CVSS', 'type': 'number'},
            {'name': 'summary', 'title': 'Summary', 'type': 'string'}],
  'name': 'specific_data.data.shodan_data.vulns',
  'title': 'Shodan Data: Vulnerabilities',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.shodan_data.vulns.vuln_name',
  'title': 'Shodan Data: Vulnerabilities: Vulnerability Name',
  'type': 'string'},
 {'branched': True,
  'name': 'specific_data.data.shodan_data.vulns.cvss',
  'title': 'Shodan Data: Vulnerabilities: CVSS',
  'type': 'number'},
 {'branched': True,
  'name': 'specific_data.data.shodan_data.vulns.summary',
  'title': 'Shodan Data: Vulnerabilities: Summary',
  'type': 'string'},
 {'enum': ['Agent',
           'Endpoint_Protection_Platform',
           'Network',
           'Firewall',
           'Manager',
           'Vulnerability_Assessment',
           'Assets',
           'UserManagement',
           'Cloud_Provider',
           'Virtualization',
           'MDM'],
  'items': {'enum': ['Agent',
                     'Endpoint_Protection_Platform',
                     'Network',
                     'Firewall',
                     'Manager',
                     'Vulnerability_Assessment',
                     'Assets',
                     'UserManagement',
                     'Cloud_Provider',
                     'Virtualization',
                     'MDM'],
            'type': 'string'},
  'name': 'specific_data.data.adapter_properties',
  'title': 'Adapter Properties',
  'type': 'array'}]