[{'format': 'image',
  'name': 'specific_data.data.image',
  'title': 'Image',
  'type': 'string'},
 {'name': 'specific_data.data.id', 'title': 'ID', 'type': 'string'},
 {'name': 'specific_data.data.user_sid', 'title': 'SID', 'type': 'string'},
 {'name': 'specific_data.data.mail', 'title': 'Mail', 'type': 'string'},
 {'name': 'specific_data.data.username',
  'title': 'User Name',
  'type': 'string'},
 {'name': 'specific_data.data.display_name',
  'title': 'Display Name',
  'type': 'string'},
 {'name': 'specific_data.data.description',
  'title': 'Description',
  'type': 'string'},
 {'name': 'specific_data.data.domain', 'title': 'Domain', 'type': 'string'},
 {'name': 'specific_data.data.is_admin', 'title': 'Is Admin', 'type': 'bool'},
 {'format': 'date-time',
  'name': 'specific_data.data.last_seen_in_devices',
  'title': 'Last Seen In Devices',
  'type': 'string'},
 {'format': 'date-time',
  'name': 'specific_data.data.last_seen',
  'title': 'Last Seen In Domain',
  'type': 'string'},
 {'format': 'table',
  'items': [{'name': 'device_caption',
             'title': 'Device Name',
             'type': 'string'}],
  'name': 'specific_data.data.associated_devices',
  'title': 'Associated Devices',
  'type': 'array'},
 {'branched': True,
  'name': 'specific_data.data.associated_devices.device_caption',
  'title': 'Associated Devices: Device Name',
  'type': 'string'},
 {'name': 'specific_data.data.is_local', 'title': 'Is Local', 'type': 'bool'},
 {'name': 'specific_data.data.is_locked', 'title': 'Is Locked', 'type': 'bool'},
 {'format': 'date-time',
  'name': 'specific_data.data.last_lockout_time',
  'title': 'Last Lockout time',
  'type': 'string'},
 {'format': 'date-time',
  'name': 'specific_data.data.password_expiration_date',
  'title': 'Password Expiration Date',
  'type': 'string'},
 {'name': 'specific_data.data.password_never_expires',
  'title': 'Password Never Expires',
  'type': 'bool'},
 {'name': 'specific_data.data.password_not_required',
  'title': 'Password Is Not Required',
  'type': 'bool'},
 {'name': 'specific_data.data.account_disabled',
  'title': 'Account Disabled',
  'type': 'bool'},
 {'format': 'date-time',
  'name': 'specific_data.data.account_expires',
  'title': 'Account Expiration Date',
  'type': 'string'},
 {'name': 'specific_data.data.logon_count',
  'title': 'Logon Count',
  'type': 'integer'},
 {'format': 'date-time',
  'name': 'specific_data.data.last_bad_logon',
  'title': 'Domain Last Bad Logon Date',
  'type': 'string'},
 {'format': 'date-time',
  'name': 'specific_data.data.last_password_change',
  'title': 'Last Password Change',
  'type': 'string'},
 {'format': 'date-time',
  'name': 'specific_data.data.last_logoff',
  'title': 'Domain Last Logoff Date',
  'type': 'string'},
 {'format': 'date-time',
  'name': 'specific_data.data.last_logon',
  'title': 'Domain Last Logon Date',
  'type': 'string'},
 {'format': 'date-time',
  'name': 'specific_data.data.last_logon_timestamp',
  'title': 'Domain Last Logon Timestamp Date',
  'type': 'string'},
 {'format': 'date-time',
  'name': 'specific_data.data.user_created',
  'title': 'User Creation Date',
  'type': 'string'},
 {'name': 'specific_data.data.user_title',
  'title': 'User Title',
  'type': 'string'},
 {'name': 'specific_data.data.user_department',
  'title': 'User Department',
  'type': 'string'},
 {'name': 'specific_data.data.user_manager',
  'title': 'User Manager Username',
  'type': 'string'},
 {'name': 'specific_data.data.user_telephone_number',
  'title': 'User Telephone Number',
  'type': 'string'},
 {'name': 'specific_data.data.user_city',
  'title': 'User City',
  'type': 'string'},
 {'name': 'specific_data.data.user_country',
  'title': 'User Country',
  'type': 'string'},
 {'name': 'specific_data.data.first_name',
  'title': 'First Name',
  'type': 'string'},
 {'name': 'specific_data.data.last_name',
  'title': 'Last Name',
  'type': 'string'},
 {'name': 'specific_data.data.employee_id',
  'title': 'Employee ID',
  'type': 'string'},
 {'name': 'specific_data.data.employee_number',
  'title': 'Employee Number',
  'type': 'string'},
 {'name': 'specific_data.data.employee_type',
  'title': 'Employee Type',
  'type': 'string'},
 {'name': 'specific_data.data.member_in_groups',
  'title': 'Groups membership (memberOf)',
  'type': 'string'},
 {'name': 'specific_data.data.member_in_groups_including_nested',
  'title': 'All Groups membership(nested memberOf)',
  'type': 'string'}]